# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d70b9fd7baf3d01ce0aaf23571e8fc545b1c2e13b9bca9280775e1f7b8e8b14149ec5e6b4036ce7d9407bda9a6e1e9d236ad13243b3a879ffa9991d4095b490

test:
  secret_key_base: 1d45b29c76c85ae1fc2f0030552946e380663514e5406acd5bafeaf5a337dd5188a87eee18b7cb80123b6601433ac8bb3998679d86cb0bc3396eb8a2fd3c99ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
