# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# Cuentas de Administradores
AdminUser.create!(email: 'jdumois@uc.cl', password: 'jdumois', password_confirmation: 'jdumois')
AdminUser.create!(email: 'alexis.torreblanca.urzua@gmail.com', password: 'alexis.torreblanca.urzua', password_confirmation: 'alexis.torreblanca.urzua')
AdminUser.create!(email: 'akimxtreme.dj@gmail.com', password: 'akimxtreme', password_confirmation: 'akimxtreme')

User.create!(email: 'webmaster@infomigra.org', password: '123456', password_confirmation: '123456')

# All Country Categories
CountryCategory.create!(id:1, name: 'Mercosur', percentage_profile: '20')
CountryCategory.create!(id:2, name: 'No mercosur', percentage_profile: '20')
CountryCategory.create!(id:3, name: 'Consular', percentage_profile: '20')

# Full Countries
Country.create!(abbreviation:'MK',name:'ARY Macedonia',flag_image:'ary_macedonia.png',country_category_id:2, name_cr:'la Macédoine', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'AF',name:'Afganistán',flag_image:'afganistan.png',country_category_id:3, name_cr:"l'Afghanistan", status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'AL',name:'Albania',flag_image:'albania.png',country_category_id:2, name_cr:"l'Albanie", status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'DE',name:'Alemania',flag_image:'alemania.png',country_category_id:2, name_cr:"l'Allemagne", status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'AD',name:'Andorra',flag_image:'andorra.png',country_category_id:2, name_cr:"Andorre", status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'AO',name:'Angola',flag_image:'angola.png',country_category_id:3, name_cr:"l'Angola", status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'AI',name:'Anguilla',flag_image:'anguilla.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'AG',name:'Antigua y Barbuda',flag_image:'antigua_y_barbuda.png',country_category_id:2, name_cr:"Antigua-et-Barbuda", status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'AN',name:'Antillas Holandesas',flag_image:'antillas_holandesas.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'AQ',name:'Antártida',flag_image:'antartida.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'SA',name:'Arabia Saudita',flag_image:'arabia_saudita.png',country_category_id:3, name_cr:"l'Arabie saoudite", status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'DZ',name:'Argelia',flag_image:'argelia.png',country_category_id:3, name_cr:"l'Algérie", status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'AR',name:'Argentina',flag_image:'argentina.png',country_category_id:1, name_cr:'Ajantinn', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'AM',name:'Armenia',flag_image:'armenia.png',country_category_id:3, name_cr:"l'Arménie", status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'AW',name:'Aruba',flag_image:'aruba.png',country_category_id:2, name_cr:'Aruba', status:true)
Country.create!(abbreviation:'AU',name:'Australia',flag_image:'australia.png',country_category_id:2, name_cr:"l'Australie", status:true, continent:'Oceanía', continent_number: 5)
Country.create!(abbreviation:'AT',name:'Austria',flag_image:'austria.png',country_category_id:2, name_cr:"l'Autriche", status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'AZ',name:'Azerbaiyán',flag_image:'azerbaiyan.png',country_category_id:3, name_cr:"l'Azerbaïdjan", status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'BS',name:'Bahamas',flag_image:'bahamas.png',country_category_id:2, name_cr:"les Bahamas", status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'BH',name:'Bahréin',flag_image:'bahrein.png',country_category_id:3, name_cr:"le Bahreïn", status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'BD',name:'Bangladesh',flag_image:'bangladesh.png',country_category_id:3, name_cr:'le Bangladesh', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'BB',name:'Barbados',flag_image:'barbados.png',country_category_id:2, name_cr:'la Barbade', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'BZ',name:'Belice',flag_image:'belice.png',country_category_id:2, name_cr:'le Belize', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'BJ',name:'Benin',flag_image:'benin.png',country_category_id:3, name_cr:'le Bénin', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'BM',name:'Bermudas',flag_image:'bermudas.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'BT',name:'Bután',flag_image:'butan.png',country_category_id:3, name_cr:'le Bhoutan', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'BY',name:'Bielorrusia',flag_image:'bielorrusia.png',country_category_id:3, name_cr:'la Biélorussie', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'BO',name:'Bolivia',flag_image:'bolivia.png',country_category_id:1, name_cr:'la Bolivie', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'BA',name:'Bosnia y Herzegovina',flag_image:'bosnia_y_herzegovina.png',country_category_id:2, name_cr:'', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'BW',name:'Botsuana',flag_image:'botsuana.png',country_category_id:3, name_cr:'le Botswana', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'BR',name:'Brasil',flag_image:'brasil.png',country_category_id:1, name_cr:'Brezil', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'BN',name:'Brunéi',flag_image:'brunei.png',country_category_id:2, name_cr:'le Brunéi', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'BG',name:'Bulgaria',flag_image:'bulgaria.png',country_category_id:2, name_cr:'la Bulgarie', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'BF',name:'Burkina Faso',flag_image:'burkina_faso.png',country_category_id:3, name_cr:'le Burkina-Faso', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'BI',name:'Burundi',flag_image:'burundi.png',country_category_id:3, name_cr:'le Burundi', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'BE',name:'Bélgica',flag_image:'belgica.png',country_category_id:2, name_cr:'la Belgique', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'CV',name:'Cabo Verde',flag_image:'cabo_verde.png',country_category_id:3, name_cr:'le Cap-Vert', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'KH',name:'Camboya',flag_image:'camboya.png',country_category_id:3, name_cr:'le Cambodge', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'CM',name:'Camerún',flag_image:'camerun.png',country_category_id:3, name_cr:'le Cameroun', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'CA',name:'Canadá',flag_image:'canada.png',country_category_id:2, name_cr:'Kanada', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'TD',name:'Chad',flag_image:'chad.png',country_category_id:3, name_cr:'le Tchad', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'CL',name:'Chile',flag_image:'chile.png',country_category_id:2, name_cr:'Chile', status:false, continent:'América', continent_number: 1)
Country.create!(abbreviation:'CN',name:'China',flag_image:'china.png',country_category_id:3, name_cr:'la Chine', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'CY',name:'Chipre',flag_image:'chipre.png',country_category_id:2, name_cr:'Chypre', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'VA',name:'Ciudad del Vaticano',flag_image:'ciudad_del_vaticano.png',country_category_id:2, name_cr:'le Vatican', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'CO',name:'Colombia',flag_image:'colombia.png',country_category_id:2, name_cr:'Kolonbi', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'KM',name:'Comoras',flag_image:'comoras.png',country_category_id:3, name_cr:'les Comores', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'CG',name:'República del Congo',flag_image:'republica_de_congo.png',country_category_id:3, name_cr:'le Congo', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'KP',name:'Corea del Norte',flag_image:'corea_del_norte.png',country_category_id:3, name_cr:'la Corée du Nord', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'KR',name:'Corea del Sur',flag_image:'corea_del_sur.png',country_category_id:2, name_cr:'la Corée du Sud', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'CR',name:'Costa Rica',flag_image:'costa_rica.png',country_category_id:2, name_cr:'le Costa Rica', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'CI',name:'Costa de Marfil',flag_image:'costa_de_marfil.png',country_category_id:3, name_cr:"la Côte d'Ivoire", status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'HR',name:'Croacia',flag_image:'croacia.png',country_category_id:2, name_cr:'la Croatie', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'CU',name:'Cuba',flag_image:'cuba.png',country_category_id:3, name_cr:'Kiba', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'DK',name:'Dinamarca',flag_image:'dinamarca.png',country_category_id:2, name_cr:'le Danemark', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'DM',name:'Dominica',flag_image:'dominica.png',country_category_id:3, name_cr:'Dominik', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'EC',name:'Ecuador',flag_image:'ecuador.png',country_category_id:2, name_cr:"l'Équateur", status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'EG',name:'Egipto',flag_image:'egipto.png',country_category_id:3, name_cr:"l'Égypte", status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'SV',name:'El Salvador',flag_image:'el_salvador.png',country_category_id:2, name_cr:'', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'AE',name:'Emiratos Árabes Unidos',flag_image:'emiratos_arabes_unidos.png',country_category_id:3, name_cr:'les Émirats arabes unis', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'ER',name:'Eritrea',flag_image:'eritrea.png',country_category_id:3, name_cr:"l'Érythrée", status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'SK',name:'Eslovaquia',flag_image:'eslovaquia.png',country_category_id:2, name_cr:'la Slovaquie', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'SI',name:'Eslovenia',flag_image:'eslovenia.png',country_category_id:2, name_cr:'la Slovénie', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'ES',name:'España',flag_image:'espana.png',country_category_id:2, name_cr:"l'Espagne", status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'US',name:'Estados Unidos',flag_image:'estados_unidos.png',country_category_id:2, name_cr:'US', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'EE',name:'Estonia',flag_image:'estonia.png',country_category_id:2, name_cr:"l'Estonie", status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'ET',name:'Etiopía',flag_image:'etiopia.png',country_category_id:3, name_cr:"l'Éthiopie", status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'PH',name:'Filipinas',flag_image:'filipinas.png',country_category_id:3, name_cr:'les Philippines', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'FI',name:'Finlandia',flag_image:'finlandia.png',country_category_id:2, name_cr:'la Finlande', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'FJ',name:'Fiyi',flag_image:'fiyi.png',country_category_id:2, name_cr:'les Fidji', status:true, continent:'Oceanía', continent_number: 5)
Country.create!(abbreviation:'FR',name:'Francia',flag_image:'francia.png',country_category_id:2, name_cr:'Lafrans', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'GA',name:'Gabón',flag_image:'gabon.png',country_category_id:3, name_cr:'le Gabon', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'GM',name:'Gambia',flag_image:'gambia.png',country_category_id:3, name_cr:'la Gambie', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'GE',name:'Georgia',flag_image:'georgia.png',country_category_id:3, name_cr:'la Géorgie', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'GH',name:'Ghana',flag_image:'ghana.png',country_category_id:3, name_cr:'le Ghana', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'GI',name:'Gibraltar',flag_image:'gibraltar.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'GD',name:'Granada',flag_image:'granada.png',country_category_id:2, name_cr:'', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'GR',name:'Grecia',flag_image:'grecia.png',country_category_id:2, name_cr:'la Grèce', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'GL',name:'Groenlandia',flag_image:'groenlandia.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'GP',name:'Guadalupe',flag_image:'guadalupe.png',country_category_id:2, name_cr:'Guadalupe', status:true)
Country.create!(abbreviation:'GU',name:'Guam',flag_image:'guam.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'GT',name:'Guatemala',flag_image:'guatemala.png',country_category_id:2, name_cr:'', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'GF',name:'Guayana Francesa',flag_image:'guayana_francesa.png',country_category_id:2, name_cr:'Franse Gwiyane', status:true)
Country.create!(abbreviation:'GN',name:'Guinea',flag_image:'guinea.png',country_category_id:3, name_cr:'la Guinée', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'GQ',name:'Guinea Ecuatorial',flag_image:'guinea_ecuatorial.png',country_category_id:2, name_cr:'la Guinée-équatoriale', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'GW',name:'Guinea-Bissau',flag_image:'guinea_bissau.png',country_category_id:3, name_cr:'la Guinée-Bissao', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'GY',name:'Guyana',flag_image:'guyana.png',country_category_id:3, name_cr:'la Guyana', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'HT',name:'Haití',flag_image:'haiti.png',country_category_id:2, name_cr:'Ayiti', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'HN',name:'Honduras',flag_image:'honduras.png',country_category_id:2, name_cr:'le Honduras', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'HK',name:'Hong Kong',flag_image:'hong_kong.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'HU',name:'Hungría',flag_image:'hungria.png',country_category_id:2, name_cr:'la Hongrie', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'IN',name:'India',flag_image:'india.png',country_category_id:3, name_cr:"l'Inde", status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'ID',name:'Indonesia',flag_image:'indonesia.png',country_category_id:2, name_cr:"l'Indonésie", status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'IQ',name:'Irak',flag_image:'irak.png',country_category_id:3, name_cr:"l'Irak", status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'IE',name:'Irlanda',flag_image:'irlanda.png',country_category_id:2, name_cr:"l'Irlande", status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'IR',name:'Irán',flag_image:'iran.png',country_category_id:3, name_cr:"l'Iran", status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'BV',name:'Isla Bouvet',flag_image:'isla_bouvet.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'NF',name:'Isla Norfolk',flag_image:'isla_norfolk.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'CX',name:'Isla de Navidad',flag_image:'isla_de_navidad.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'IS',name:'Islandia',flag_image:'islandia.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'KY',name:'Islas Caimán',flag_image:'islas_caiman.png',country_category_id:2, name_cr:'Zile Kayiman', status:true)
Country.create!(abbreviation:'CC',name:'Islas Cocos',flag_image:'islas_cocos.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'CK',name:'Islas Cook',flag_image:'islas_cook.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'FO',name:'Islas Feroe',flag_image:'islas_feroe.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'GS',name:'Islas Georgias del Sur y Sandwich del Sur',flag_image:'islas_georgias_del_sur_y_sandwich_del_sur.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'AX',name:'Islas Gland',flag_image:'islas_gland.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'HM',name:'Islas Heard y McDonald',flag_image:'islas_heard_y_mcdonald.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'FK',name:'Islas Malvinas',flag_image:'islas_malvinas.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'MP',name:'Islas Marianas del Norte',flag_image:'islas_marianas_del_norte.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'MH',name:'Islas Marshall',flag_image:'islas_marshall.png',country_category_id:3, name_cr:'les Îles Marshall', status:true, continent:'Oceanía', continent_number: 5)
Country.create!(abbreviation:'PN',name:'Islas Pitcairn',flag_image:'islas_pitcairn.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'SB',name:'Islas Salomón',flag_image:'islas_salomon.png',country_category_id:3, name_cr:'les Îles Salomon', status:true, continent:'Oceanía', continent_number: 5)
Country.create!(abbreviation:'TC',name:'Islas Turcas y Caicos',flag_image:'islas_turcas_y_caicos.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'VG',name:'Islas Vírgenes Británicas',flag_image:'islas_virgenes_britanicas.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'VI',name:'Islas Vírgenes de los Estados Unidos',flag_image:'islas_virgenes_de_los_estados_unidos.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'UM',name:'Islas ultramarinas de Estados Unidos',flag_image:'islas_ultramarinas_de_estados_unidos.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'IL',name:'Israel',flag_image:'israel.png',country_category_id:2, name_cr:'Israël', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'IT',name:'Italia',flag_image:'italia.png',country_category_id:2, name_cr:"l'Italie", status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'JM',name:'Jamaica',flag_image:'jamaica.png',country_category_id:2, name_cr:'la Jamaïque', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'JP',name:'Japón',flag_image:'japon.png',country_category_id:2, name_cr:'le Japon', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'JO',name:'Jordania',flag_image:'jordania.png',country_category_id:3, name_cr:'la Jordanie', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'KZ',name:'Kazajstán',flag_image:'kazajstan.png',country_category_id:3, name_cr:'le Kazakhstan', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'KE',name:'Kenia',flag_image:'kenia.png',country_category_id:3, name_cr:'le Kenya', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'KG',name:'Kirguistán',flag_image:'kirguistan.png',country_category_id:3, name_cr:'', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'KI',name:'Kiribati',flag_image:'kiribati.png',country_category_id:3, name_cr:'kiribati', status:true, continent:'Oceanía', continent_number: 5)
Country.create!(abbreviation:'KW',name:'Kuwait',flag_image:'kuwait.png',country_category_id:3, name_cr:'le Koweït', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'LA',name:'Laos',flag_image:'laos.png',country_category_id:3, name_cr:'le Laos', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'LS',name:'Lesotho',flag_image:'lesotho.png',country_category_id:3, name_cr:'le Lesotho', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'LV',name:'Letonia',flag_image:'letonia.png',country_category_id:2, name_cr:'la Lettonie', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'LR',name:'Liberia',flag_image:'liberia.png',country_category_id:3, name_cr:'le Libéria', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'LY',name:'Libia',flag_image:'libia.png',country_category_id:3, name_cr:'la Libye', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'LI',name:'Liechtenstein',flag_image:'liechtenstein.png',country_category_id:2, name_cr:'le Lichtenstein', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'LT',name:'Lituania',flag_image:'lituania.png',country_category_id:2, name_cr:'la Lituanie', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'LU',name:'Luxemburgo',flag_image:'luxemburgo.png',country_category_id:2, name_cr:'le Luxembourg', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'LB',name:'Líbano',flag_image:'libano.png',country_category_id:3, name_cr:'le Liban', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'MO',name:'Macao',flag_image:'macao.png',country_category_id:2, name_cr:'Madagascar', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'MG',name:'Madagascar',flag_image:'madagascar.png',country_category_id:3, name_cr:'', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'MY',name:'Malasia',flag_image:'malasia.png',country_category_id:2, name_cr:'la Malaisie', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'MW',name:'Malawi',flag_image:'malawi.png',country_category_id:3, name_cr:'le Malawi', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'MV',name:'Maldivas',flag_image:'maldivas.png',country_category_id:3, name_cr:'les Maldives', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'MT',name:'Malta',flag_image:'malta.png',country_category_id:2, name_cr:'Malte', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'ML',name:'Malí',flag_image:'mali.png',country_category_id:3, name_cr:'le Mali', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'MA',name:'Marruecos',flag_image:'marruecos.png',country_category_id:3, name_cr:'le Maroc', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'MQ',name:'Martinica',flag_image:'martinica.png',country_category_id:2, name_cr:'Martinik', status:true)
Country.create!(abbreviation:'MU',name:'Mauricio',flag_image:'mauricio.png',country_category_id:2, name_cr:"l'Île Maurice", status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'MR',name:'Mauritania',flag_image:'mauritania.png',country_category_id:3, name_cr:'la Mauritanie', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'YT',name:'Mayotte',flag_image:'mayotte.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'FM',name:'Micronesia',flag_image:'micronesia.png',country_category_id:3, name_cr:'la Micronésie', status:true, continent:'Oceanía', continent_number: 5)
Country.create!(abbreviation:'MD',name:'Moldavia',flag_image:'moldavia.png',country_category_id:2, name_cr:'la Moldavie', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'MN',name:'Mongolia',flag_image:'mongolia.png',country_category_id:2, name_cr:'la Mongolie', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'MS',name:'Montserrat',flag_image:'montserrat.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'MZ',name:'Mozambique',flag_image:'mozambique.png',country_category_id:3, name_cr:'le Mozambique', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'MM',name:'Myanmar',flag_image:'myanmar.png',country_category_id:3, name_cr:'la Birmanie', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'MX',name:'México',flag_image:'mexico.png',country_category_id:2, name_cr:'Meksik', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'MC',name:'Mónaco',flag_image:'monaco.png',country_category_id:2, name_cr:'Monaco', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'NA',name:'Namibia',flag_image:'namibia.png',country_category_id:3, name_cr:'la Namibie', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'NR',name:'Nauru',flag_image:'nauru.png',country_category_id:3, name_cr:'la Nauru', status:true, continent:'Oceanía', continent_number: 5)
Country.create!(abbreviation:'NP',name:'Nepal',flag_image:'nepal.png',country_category_id:3, name_cr:'le Népal', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'NI',name:'Nicaragua',flag_image:'nicaragua.png',country_category_id:2, name_cr:'le Nicaragua', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'NG',name:'Nigeria',flag_image:'nigeria.png',country_category_id:3, name_cr:'le Nigeria', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'NU',name:'Niue',flag_image:'niue.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'NO',name:'Noruega',flag_image:'noruega.png',country_category_id:2, name_cr:'la Norvège', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'NC',name:'Nueva Caledonia',flag_image:'nueva_caledonia.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'NZ',name:'Nueva Zelanda',flag_image:'nueva_zelanda.png',country_category_id:2, name_cr:'la Nouvelle-Zélande', status:true, continent:'Oceanía', continent_number: 5)
Country.create!(abbreviation:'NE',name:'Níger',flag_image:'niger.png',country_category_id:3, name_cr:'le Niger', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'OM',name:'Omán',flag_image:'oman.png',country_category_id:3, name_cr:"l'Oman", status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'PK',name:'Pakistán',flag_image:'pakistan.png',country_category_id:3, name_cr:'le Pakistan', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'PW',name:'Palaos',flag_image:'palaos.png',country_category_id:3, name_cr:'', status:true, continent:'Oceanía', continent_number: 5)
Country.create!(abbreviation:'PS',name:'Palestina',flag_image:'palestina.png',country_category_id:3, name_cr:'', status:true)
Country.create!(abbreviation:'PA',name:'Panamá',flag_image:'panama.png',country_category_id:2, name_cr:'le Panama', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'PG',name:'Papúa Nueva Guinea',flag_image:'papua_nueva_guinea.png',country_category_id:3, name_cr:'la Papouaise-
Nouvelle-Guinée', status:true, continent:'Oceanía', continent_number: 5)
Country.create!(abbreviation:'PY',name:'Paraguay',flag_image:'paraguay.png',country_category_id:1, name_cr:'le Paraguay', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'NL',name:'Países Bajos',flag_image:'paises_bajos.png',country_category_id:2, name_cr:'', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'PE',name:'Perú',flag_image:'peru.png',country_category_id:2, name_cr:'le Pérou', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'PF',name:'Polinesia Francesa',flag_image:'polinesia_francesa.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'PL',name:'Polonia',flag_image:'polonia.png',country_category_id:2, name_cr:'la Pologne', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'PT',name:'Portugal',flag_image:'portugal.png',country_category_id:2, name_cr:'le Portugal', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'PR',name:'Puerto Rico',flag_image:'puerto_rico.png',country_category_id:2, name_cr:'Puerto Rico', status:true)
Country.create!(abbreviation:'QA',name:'Qatar',flag_image:'qatar.png',country_category_id:3, name_cr:'le Qatar', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'GB',name:'Reino Unido',flag_image:'reino_unido.png',country_category_id:2, name_cr:"le Royaume-Uni", status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'CF',name:'República Centroafricana',flag_image:'republica_centroafricana.png',country_category_id:3, name_cr:'la République centrafricaine', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'CZ',name:'República Checa',flag_image:'republica_checa.png',country_category_id:2, name_cr:'la République tchèque', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'CD',name:'República Democrática del Congo',flag_image:'republica_democratica_del_congo.png',country_category_id:3, name_cr:'', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'DO',name:'República Dominicana',flag_image:'republica_dominicana.png',country_category_id:3, name_cr:'Dominikèn repiblik', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'RE',name:'Reunión',flag_image:'reunion.png',country_category_id:2, name_cr:'Reunión', status:true)
Country.create!(abbreviation:'RW',name:'Ruanda',flag_image:'ruanda.png',country_category_id:3, name_cr:'le Rwanda', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'RO',name:'Rumanía',flag_image:'rumania.png',country_category_id:2, name_cr:'la Roumanie', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'RU',name:'Rusia',flag_image:'rusia.png',country_category_id:2, name_cr:'la Russie', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'EH',name:'Sahara Occidental',flag_image:'sahara_occidental.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'WS',name:'Samoa',flag_image:'samoa.png',country_category_id:3, name_cr:'', status:true, continent:'Oceanía', continent_number: 5)
Country.create!(abbreviation:'AS',name:'Samoa Americana',flag_image:'samoa_americana.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'KN',name:'San Cristóbal y Nevis',flag_image:'san_cristobal_y_nevis.png',country_category_id:2, name_cr:'Saint-Christophe
-et-Niévès', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'SM',name:'San Marino',flag_image:'san_marino.png',country_category_id:2, name_cr:'Saint-Marin', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'PM',name:'San Pedro y Miquelón',flag_image:'san_pedro_y_miquelon.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'VC',name:'San Vicente y las Granadinas',flag_image:'san_vicente_y_las_granadinas.png',country_category_id:2, name_cr:'', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'SH',name:'Santa Helena',flag_image:'santa_helena.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'LC',name:'Santa Lucía',flag_image:'santa_lucia.png',country_category_id:2, name_cr:'Saint Lucia', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'ST',name:'Santo Tomé y Príncipe',flag_image:'santo_tome_y_principe.png',country_category_id:3, name_cr:'', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'SN',name:'Senegal',flag_image:'senegal.png',country_category_id:3, name_cr:'', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'CS',name:'Serbia y Montenegro',flag_image:'serbia_y_montenegro.png',country_category_id:2, name_cr:'', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'SC',name:'Seychelles',flag_image:'seychelles.png',country_category_id:3, name_cr:'seychelles', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'SL',name:'Sierra Leona',flag_image:'sierra_leona.png',country_category_id:3, name_cr:'', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'SG',name:'Singapur',flag_image:'singapur.png',country_category_id:2, name_cr:'Singapour', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'SY',name:'Siria',flag_image:'siria.png',country_category_id:3, name_cr:'la Syrie', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'SO',name:'Somalia',flag_image:'somalia.png',country_category_id:3, name_cr:'la Somalie', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'LK',name:'Sri Lanka',flag_image:'sri_lanka.png',country_category_id:3, name_cr:'le Sri Lanka', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'SZ',name:'Suazilandia',flag_image:'suazilandia.png',country_category_id:3, name_cr:'', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'ZA',name:'Sudáfrica',flag_image:'sudafrica.png',country_category_id:2, name_cr:"l'Afrique du Sud", status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'SD',name:'Sudán',flag_image:'sudan.png',country_category_id:3, name_cr:'le Soudan', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'SE',name:'Suecia',flag_image:'suecia.png',country_category_id:2, name_cr:'la Suède', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'CH',name:'Suiza',flag_image:'suiza.png',country_category_id:2, name_cr:'la Suisse', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'SR',name:'Surinam',flag_image:'surinam.png',country_category_id:3, name_cr:'le Surinam', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'SJ',name:'Svalbard y Jan Mayen',flag_image:'svalbard_y_jan_mayen.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'TH',name:'Tailandia',flag_image:'tailandia.png',country_category_id:2, name_cr:'la Thaïlande', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'TW',name:'Taiwán',flag_image:'taiwan.png',country_category_id:3, name_cr:'', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'TZ',name:'Tanzania',flag_image:'tanzania.png',country_category_id:3, name_cr:'la Tanzanie', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'TJ',name:'Tayikistán',flag_image:'tayikistan.png',country_category_id:3, name_cr:'le Tadjikistan', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'IO',name:'Territorio Británico del Océano Índico',flag_image:'territorio_britanico_del_oceano_indico.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'TF',name:'Territorios Australes Franceses',flag_image:'territorios_australes_franceses.png',country_category_id:2, name_cr:'', status:true)
Country.create!(abbreviation:'TL',name:'Timor Oriental',flag_image:'timor_oriental.png',country_category_id:3, name_cr:'', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'TG',name:'Togo',flag_image:'togo.png',country_category_id:3, name_cr:'le Togo', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'TK',name:'Tokelau',flag_image:'tokelau.png',country_category_id:2, name_cr:'', status:true, continent:'Oceanía', continent_number: 5)
Country.create!(abbreviation:'TO',name:'Tonga',flag_image:'tonga.png',country_category_id:2, name_cr:'les Tonga', status:true, continent:'Oceanía', continent_number: 5)
Country.create!(abbreviation:'TT',name:'Trinidad y Tobago',flag_image:'trinidad_y_tobago.png',country_category_id:2, name_cr:'Trinité-et-Tobago', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'TM',name:'Turkmenistán',flag_image:'turkmenistan.png',country_category_id:3, name_cr:'le Turkménistan', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'TR',name:'Turquía',flag_image:'turquia.png',country_category_id:2, name_cr:'la Turquie', status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'TV',name:'Tuvalu',flag_image:'tuvalu.png',country_category_id:3, name_cr:'Tuvalu', status:true, continent:'Oceanía', continent_number: 5)
Country.create!(abbreviation:'TN',name:'Túnez',flag_image:'tunez.png',country_category_id:3, name_cr:'la Tunisie', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'UA',name:'Ucrania',flag_image:'ucrania.png',country_category_id:3, name_cr:"l'Ukraine", status:true, continent:'Europa', continent_number: 2)
Country.create!(abbreviation:'UG',name:'Uganda',flag_image:'uganda.png',country_category_id:2, name_cr:"l'Ouganda", status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'UY',name:'Uruguay',flag_image:'uruguay.png',country_category_id:1, name_cr:"l'Uruguay", status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'UZ',name:'Uzbekistán',flag_image:'uzbekistan.png',country_category_id:3, name_cr:"l'Ouzbékistan", status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'VU',name:'Vanuatu',flag_image:'vanuatu.png',country_category_id:3, name_cr:'Vanuatu', status:true, continent:'Oceanía', continent_number: 5)
Country.create!(abbreviation:'VE',name:'Venezuela',flag_image:'venezuela.png',country_category_id:1, name_cr:'Venezyela', status:true, continent:'América', continent_number: 1)
Country.create!(abbreviation:'VN',name:'Vietnam',flag_image:'vietnam.png',country_category_id:3, name_cr:'le Viêt-Nam', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'WF',name:'Wallis y Futuna',flag_image:'wallis_y_futuna.png',country_category_id:2, name_cr:'', status:true, continent:'Oceanía', continent_number: 5)
Country.create!(abbreviation:'YE',name:'Yemen',flag_image:'yemen.png',country_category_id:3, name_cr:'le Yémen', status:true, continent:'Asia', continent_number: 3)
Country.create!(abbreviation:'DJ',name:'Yibuti',flag_image:'yibuti.png',country_category_id:3, name_cr:'Djibouti', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'ZM',name:'Zambia',flag_image:'zambia.png',country_category_id:3, name_cr:'la Zambie', status:true, continent:'África', continent_number: 4)
Country.create!(abbreviation:'ZW',name:'Zimbabue',flag_image:'zimbabue.png',country_category_id:3, name_cr:'le Zimbabwe', status:true, continent:'África', continent_number: 4)

# All Regions
Region.create!( id:1, name:'ARICA Y PARINACOTA', roman_number:'XV', num_provinces:2, num_communes:4)
Region.create!( id:2, name:'TARAPACÁ', roman_number:'I', num_provinces:2, num_communes:7)
Region.create!( id:3, name:'ANTOFAGASTA', roman_number:'II', num_provinces:3, num_communes:9)
Region.create!( id:4, name:'ATACAMA ', roman_number:'III', num_provinces:3, num_communes:9)
Region.create!( id:5, name:'COQUIMBO ', roman_number:'IV', num_provinces:3, num_communes:15)
Region.create!( id:6, name:'VALPARAÍSO ', roman_number:'V', num_provinces:8, num_communes:38)
Region.create!( id:7, name:'DEL LIBERTADOR GRAL. BERNARDO OHIGGINS ', roman_number:'VI', num_provinces:3, num_communes:33)
Region.create!( id:8, name:'DEL MAULE', roman_number:'VII', num_provinces:4, num_communes:30)
Region.create!( id:9, name:'DEL BIOBÍO ', roman_number:'VIII', num_provinces:4, num_communes:54)
Region.create!( id:10, name:'DE LA ARAUCANÍA', roman_number:'IX', num_provinces:2, num_communes:32)
Region.create!( id:11, name:'DE LOS RÍOS', roman_number:'XIV', num_provinces:2, num_communes:12)
Region.create!( id:12, name:'DE LOS LAGOS', roman_number:'X', num_provinces:4, num_communes:30)
Region.create!( id:13, name:'AISÉN DEL GRAL. CARLOS IBAÑEZ DEL CAMPO ', roman_number:'XI', num_provinces:4, num_communes:10)
Region.create!( id:14, name:'MAGALLANES Y DE LA ANTÁRTICA CHILENA', roman_number:'XII', num_provinces:4, num_communes:11)
Region.create!( id:15, name:'METROPOLITANA DE SANTIAGO', roman_number:'RM', num_provinces:6, num_communes:52)
